"""Draw the brand SVGs (favicon, apple-touch icon, OG card) with text converted to outlines.

Favicons and OG renderers cannot load web fonts, so every glyph is a path taken from the site's
own Source Serif 4 variable font at a fixed weight and optical size. The output SVGs are
committed; `pnpm gen:brand` then copies/rasterises them into public/.

    uv run --no-project --with 'fonttools[woff]' --with uharfbuzz python scripts/brand/build_glyphs.py
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import RecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
FONT = ROOT / "src/assets/fonts/source-serif-4-latin-opsz-normal.woff2"
OUT = Path(__file__).resolve().parent

# Site palette (src/styles/global.css).
LIGHT = {"bg": "#fbfaf6", "ink": "#1c1b19", "muted": "#5b5953", "faint": "#767269", "rule": "#e6e3dc"}
DARK = {"bg": "#161513", "ink": "#ece9e2"}

TITLE = "Oh Tien Cheng"
# Generated files are kept byte-for-byte as written so reruns produce no diff.
HEADER = "<!-- biome-ignore format: generated by scripts/brand/build_glyphs.py -->\n"


def _load_face() -> hb.Face:
    # HarfBuzz cannot read WOFF2, so decompress to plain sfnt bytes first.
    buf = io.BytesIO()
    font = TTFont(FONT)
    font.flavor = None
    font.save(buf)
    return hb.Face(buf.getvalue())


FACE = _load_face()
UPEM = FACE.upem


def _num(value: float) -> str:
    text = f"{value:.2f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


@dataclass
class Outline:
    recording: RecordingPen
    advance: float  # in font units

    def bounds(self) -> tuple[float, float, float, float]:
        pen = BoundsPen(None)
        self.recording.replay(pen)
        assert pen.bounds is not None
        return pen.bounds


def outline(text: str, wght: float, opsz: float, tracking: float = 0.0) -> Outline:
    """Shape `text` and record its outlines in font units (y up), baseline at 0."""
    font = hb.Font(FACE)
    font.set_variations({"wght": wght, "opsz": opsz})
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(font, buf, {"kern": True, "liga": True})

    rec = RecordingPen()
    x = 0.0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        pen = TransformPen(rec, (1, 0, 0, 1, x + pos.x_offset, pos.y_offset))
        font.draw_glyph_with_pen(info.codepoint, pen)
        x += pos.x_advance + tracking * UPEM
    return Outline(rec, x - tracking * UPEM)


def path_d(o: Outline, size: float, x: float, baseline: float) -> str:
    """SVG path data for `o` scaled to `size` px, left edge at x, on the given baseline."""
    scale = size / UPEM
    svg = SVGPathPen(None, ntos=_num)
    o.recording.replay(TransformPen(svg, (scale, 0, 0, -scale, x, baseline)))
    return svg.getCommands()


def width(o: Outline, size: float) -> float:
    return o.advance * size / UPEM


def centred_monogram(box: float, fit: float) -> str:
    """"tc" centred on its ink bounds inside a `box`-sized square, filling `fit` of its width."""
    o = outline("tc", wght=600, opsz=32, tracking=-0.02)
    x0, y0, x1, y1 = o.bounds()
    size = fit * box * UPEM / (x1 - x0)
    scale = size / UPEM
    ink_w, ink_h = (x1 - x0) * scale, (y1 - y0) * scale
    x = (box - ink_w) / 2 - x0 * scale
    baseline = (box + ink_h) / 2 + y0 * scale
    return path_d(o, size, x, baseline)


def favicon() -> str:
    d = centred_monogram(64, 0.64)
    return f"""{HEADER}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<title>{TITLE}</title>
<style>
.bg{{fill:{LIGHT["bg"]}}}.fg{{fill:{LIGHT["ink"]}}}
@media (prefers-color-scheme:dark){{.bg{{fill:{DARK["bg"]}}}.fg{{fill:{DARK["ink"]}}}}}
</style>
<rect class="bg" width="64" height="64" rx="14"/>
<path class="fg" d="{d}"/>
</svg>
"""


def touch_icon() -> str:
    # iOS rounds the corners itself, so the square stays square.
    d = centred_monogram(180, 0.56)
    return f"""{HEADER}<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 180 180">
<title>{TITLE}</title>
<rect width="180" height="180" fill="{LIGHT["bg"]}"/>
<path fill="{LIGHT["ink"]}" d="{d}"/>
</svg>
"""


def og_card() -> str:
    w, h, margin = 1200, 630, 96
    name = outline("Oh Tien Cheng", wght=600, opsz=60, tracking=-0.01)
    tagline_text = "Applied ML systems: search, evaluation, and production LLM tooling."
    tagline_size = 36.0
    tagline = outline(tagline_text, wght=400, opsz=36)
    # Keep the tagline on one line inside the margins.
    while width(tagline, tagline_size) > w - 2 * margin:
        tagline_size -= 1
    domain = outline("tiencheng.dev", wght=400, opsz=28)
    name_size = 104.0
    return f"""{HEADER}<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">
<title>{TITLE}</title>
<rect width="{w}" height="{h}" fill="{LIGHT["bg"]}"/>
<path fill="{LIGHT["ink"]}" d="{path_d(name, name_size, margin, 272)}"/>
<path fill="{LIGHT["muted"]}" d="{path_d(tagline, tagline_size, margin, 344)}"/>
<rect x="{margin}" y="466" width="{w - 2 * margin}" height="2" fill="{LIGHT["rule"]}"/>
<path fill="{LIGHT["faint"]}" d="{path_d(domain, 28, margin, 526)}"/>
</svg>
"""


def main() -> None:
    for filename, content in {
        "favicon.svg": favicon(),
        "apple-touch-icon.svg": touch_icon(),
        "og.svg": og_card(),
    }.items():
        (OUT / filename).write_text(content)
        print(f"Wrote {OUT / filename}")


if __name__ == "__main__":
    main()
