/**
 * Writes the JSON Schema for the résumé snapshot to src/data/resume/schema.json.
 * The resume repo validates its export against this file before syncing, and CI fails if the
 * committed copy is stale (`pnpm gen:schema && git diff --exit-code`).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { z } from "astro/zod";
import { ResumeSchema } from "../src/lib/resume-schema.ts";

const out = fileURLToPath(new URL("../src/data/resume/schema.json", import.meta.url));

const schema = {
  ...z.toJSONSchema(ResumeSchema, { target: "draft-2020-12", io: "input" }),
  title: "Resume snapshot",
  description:
    "Subset of the RenderCV `cv` object read by tiencheng.dev. Generated by scripts/gen-schema.ts; do not edit.",
};

writeFileSync(out, `${JSON.stringify(schema, null, 2)}\n`);
console.log(`Wrote ${out}`);
