#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Post-merge setup for tiencheng.dev: Cloudflare Workers deploys, the domain cutover from Pages,
# and the resume → portfolio sync. Run from anywhere in the portfolio checkout:
#   ./scripts/setup-wizard.sh
# Stages run in order; see README.md ("After merging") and docs/adr/ for the why.

cd "$(dirname "$0")/.."

PORTFOLIO_REPO="Tien-Cheng/portfolio"
RESUME_REPO="Tien-Cheng/resume"
DOMAIN="tiencheng.dev"
WORKER_NAME="portfolio"
PORTFOLIO_PR_BRANCH="feat/revamp"
RESUME_PR_BRANCH="feat/portfolio-sync"
DASH="https://dash.cloudflare.com/?to=/:account"

gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# set_repo_secret REPO NAME VALUE: like set_secret, but for an explicit repository.
set_repo_secret() {
  local repo="$1" name="$2" value="$3"
  if gh_ready && printf '%s' "$value" | gh secret set "$name" -R "$repo" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$repo:$name")
    printf '  %s✓ set%s secret %s on %s\n' "$GREEN" "$RESET" "$name" "$repo"
  else
    SKIPPED+=("secret $name on $repo (gh secret set $name -R $repo)")
    warn "couldn't set secret $name on $repo; set it later"
  fi
}

# set_repo_var REPO NAME VALUE: like set_var, but for an explicit repository.
set_repo_var() {
  local repo="$1" name="$2" value="$3"
  if gh_ready && gh variable set "$name" -R "$repo" --body "$value" >/dev/null 2>&1; then
    printf '  %s✓ set%s variable %s on %s\n' "$GREEN" "$RESET" "$name" "$repo"
  else
    SKIPPED+=("variable $name on $repo (gh variable set $name -R $repo)")
    warn "couldn't set variable $name on $repo; set it later"
  fi
}

# run CMD...: echo a command, then run it.
run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  "$@"
}

# watch_latest_run REPO WORKFLOW BRANCH: follow the newest run of a workflow until it ends.
watch_latest_run() {
  local repo="$1" workflow="$2" branch="$3" id
  sleep 5
  id=$(gh run list -R "$repo" --workflow "$workflow" --branch "$branch" -L 1 \
    --json databaseId -q '.[0].databaseId' 2>/dev/null || true)
  if [[ -z "$id" ]]; then
    warn "no $workflow run found on $repo@$branch yet; check https://github.com/$repo/actions"
    return 0
  fi
  if gh run watch "$id" -R "$repo" --exit-status; then
    printf '  %s✓ run %s passed%s\n' "$GREEN" "$id" "$RESET"
  else
    warn "run $id did not pass: https://github.com/$repo/actions/runs/$id"
    confirm "Continue anyway?" || exit 1
  fi
}

# http_status URL: status code of a GET without following redirects.
http_status() { curl -s -o /dev/null -w '%{http_code}' "$1" || true; }


# ── 1 ──────────────────────────────────────────────────────────────────
stage_preflight() {
  stage "Preflight"
  say "Checking the tools this wizard uses."
  missing=()
  for tool in gh pnpm curl ssh-keygen git; do
    command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
  done
  if (( ${#missing[@]} )); then
    warn "missing: ${missing[*]}. Install them and re-run."
    exit 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh is not logged in. Run: gh auth login"
    exit 1
  fi
  printf '  %s✓%s gh, pnpm, curl, ssh-keygen and git are ready\n' "$GREEN" "$RESET"
  if [[ ! -f wrangler.jsonc ]]; then
    warn "wrangler.jsonc is missing. Check out $PORTFOLIO_PR_BRANCH (or main after the merge)."
    exit 1
  fi
  note "Repositories: $PORTFOLIO_REPO (public site), $RESUME_REPO (private resume)."
  note "Stopped part-way? Re-run with a stage number to resume: ./scripts/setup-wizard.sh 5"
  pause
}

# ── 2 ──────────────────────────────────────────────────────────────────
stage_cloudflare_token() {
  stage "Cloudflare API token and account ID for GitHub Actions"
  say "CI deploys with an account API token that can edit Workers and nothing else."
  open_url "$DASH/api-tokens"
  step "Account API tokens → Create Token → Create Custom Token."
  step "Name it: portfolio GitHub Actions"
  step "Permission: Workers → Editor, scoped to all Workers in the account"
  note "  (older screens call this: Account · Workers Scripts · Edit)"
  step "Permission: Zone · Workers Routes · Edit, zone $DOMAIN"
  note "  (needed once wrangler.jsonc declares the $DOMAIN custom domain)"
  step "Account resources: only your account. No IP filter, no expiry needed."
  step "Create the token and copy it. Cloudflare shows it once."
  ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
  say ""
  step "Your account ID is on Workers & Pages → Overview (right-hand column), or in the URL."
  ask CLOUDFLARE_ACCOUNT_ID "Paste the account ID:"
  write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
  if [[ -n "$CLOUDFLARE_API_TOKEN" ]]; then
    verify=$(curl -s -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
      "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/tokens/verify" || true)
    if [[ "$verify" != *'"success":true'* ]]; then
      verify=$(curl -s -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
        "https://api.cloudflare.com/client/v4/user/tokens/verify" || true)
    fi
    if [[ "$verify" == *'"status":"active"'* ]]; then
      printf '  %s✓%s token is active\n' "$GREEN" "$RESET"
    else
      warn "Cloudflare did not confirm this token as active. Check it before continuing."
      confirm "Store it anyway?" || exit 1
    fi
    set_repo_secret "$PORTFOLIO_REPO" CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
  else
    warn "no token entered; leaving the existing CLOUDFLARE_API_TOKEN secret as it is"
  fi
  set_repo_secret "$PORTFOLIO_REPO" CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
  note "The token is not written to .env: local wrangler should use your own login."
  pause
}

# ── 3 ──────────────────────────────────────────────────────────────────
stage_first_deploy() {
  stage "Create the Worker with a one-off deploy"
  say "The CI token can deploy an existing Worker but cannot create one."
  say "This deploy uses your own Cloudflare login to create '$WORKER_NAME' on workers.dev."
  whoami_out=$(env -u CLOUDFLARE_API_TOKEN pnpm exec wrangler whoami 2>&1 || true)
  if [[ "$whoami_out" == *"not authenticated"* ]]; then
    say "wrangler is not logged in; a browser window will ask you to authorise it."
    run env -u CLOUDFLARE_API_TOKEN pnpm exec wrangler login
  fi
  if confirm "Install, build and run 'wrangler deploy' now?"; then
    deploy_log=$(mktemp)
    run pnpm install --frozen-lockfile
    run pnpm build
    env -u CLOUDFLARE_API_TOKEN pnpm exec wrangler deploy 2>&1 | tee "$deploy_log"
    WORKERS_DEV_URL=$(grep -Eo 'https://[A-Za-z0-9.-]+\.workers\.dev' "$deploy_log" | head -n1 || true)
    rm -f "$deploy_log"
    if [[ -n "$WORKERS_DEV_URL" ]]; then
      say ""
      say "Checking $WORKERS_DEV_URL"
      for path in / /cv /projects/owlshield /resume /cv.pdf /no-such-page; do
        printf '  %-22s %s\n' "$path" "$(http_status "$WORKERS_DEV_URL$path")"
      done
      note "Expect 200 for the pages, 301 for /resume, 302 for /cv.pdf, 404 for /no-such-page."
      open_url "$WORKERS_DEV_URL"
    else
      warn "couldn't find the workers.dev URL in the output; find it under Workers & Pages → $WORKER_NAME."
    fi
    confirm "Does the site look right on workers.dev?" || exit 1
  else
    SKIPPED+=("one-off wrangler deploy to create the Worker")
  fi
}

# ── 4 ──────────────────────────────────────────────────────────────────
stage_merge_portfolio() {
  stage "Merge the portfolio PR"
  PORTFOLIO_PR_URL=$(gh pr view "$PORTFOLIO_PR_BRANCH" -R "$PORTFOLIO_REPO" --json url -q .url 2>/dev/null || true)
  if [[ -n "$PORTFOLIO_PR_URL" ]]; then
    open_url "$PORTFOLIO_PR_URL"
  else
    warn "no open PR found for $PORTFOLIO_PR_BRANCH; open it from https://github.com/$PORTFOLIO_REPO/pulls"
  fi
  step "Wait for the 'check' job to go green and the preview comment to appear."
  note "If CI ran before the secrets existed, re-run the preview job from the Checks tab."
  step "Open the preview URL from the comment and look it over."
  step "Merge the PR."
  pause "Press Enter once the PR is merged"
  if confirm "Watch the production deploy on main now?"; then
    watch_latest_run "$PORTFOLIO_REPO" ci.yml main
  fi
}

# ── 5 ──────────────────────────────────────────────────────────────────
stage_move_domain() {
  stage "Move $DOMAIN from Pages to the Worker"
  warn "$DOMAIN will be down for a few minutes while the new certificate is issued."
  confirm "Start the cutover now?" || exit 1
  open_url "$DASH/workers-and-pages"
  step "Open the old Pages project → Custom domains → $DOMAIN → ⋯ → Remove domain."
  step "Go to $DOMAIN → DNS → Records. If a CNAME for $DOMAIN (pointing at *.pages.dev)"
  step "is still there, delete it. The Worker cannot claim the hostname while it exists."
  note "  If www.$DOMAIN also pointed at Pages, deal with it the same way or redirect it."
  step "Back in Workers & Pages → $WORKER_NAME → Settings → Domains & Routes → Add → Custom domain."
  step "Enter $DOMAIN and add it."
  pause "Press Enter once the custom domain shows as added"
  say "Waiting for https://$DOMAIN to serve the Worker (up to 10 minutes; Ctrl-C to stop)."
  live=false
  for _ in $(seq 1 60); do
    if [[ "$(http_status "https://$DOMAIN/cv")" == "200" && "$(http_status "https://$DOMAIN/cv.pdf")" == "302" ]]; then
      live=true
      break
    fi
    printf '.'
    sleep 10
  done
  printf '\n'
  if $live; then
    printf '  %s✓%s https://%s is served by the Worker\n' "$GREEN" "$RESET" "$DOMAIN"
    open_url "https://$DOMAIN"
  else
    warn "https://$DOMAIN isn't answering like the Worker yet. Check the custom domain status."
    confirm "Continue anyway?" || exit 1
  fi
}

# ── 6 ──────────────────────────────────────────────────────────────────
stage_declare_domain() {
  stage "Declare the custom domain in wrangler.jsonc"
  say "Now that the Worker owns $DOMAIN, record it in config so deploys keep it attached."
  if grep -q '^  "routes"' wrangler.jsonc; then
    printf '  %s✓%s wrangler.jsonc already declares routes\n' "$GREEN" "$RESET"
  elif [[ -n "$(git status --porcelain)" ]]; then
    warn "your working tree has uncommitted changes, so this step is manual:"
    say "on a branch from main, change the \"previews\" line in wrangler.jsonc to:"
    say "  \"previews\": {},"
    say "  \"routes\": [{ \"pattern\": \"$DOMAIN\", \"custom_domain\": true }]"
    say "then commit, push and open a PR."
    SKIPPED+=("add the $DOMAIN custom_domain route to wrangler.jsonc")
    pause
  elif confirm "Create branch chore/worker-custom-domain from main, edit, commit, push and open a PR?"; then
    run git fetch origin main
    run git switch -c chore/worker-custom-domain origin/main
    # Add the route after "previews" and drop the "No routes yet" comment that explained its absence.
    DOMAIN="$DOMAIN" perl -0pi -e '
      s/"previews": \{\}\n/"previews": {},\n  "routes": [{ "pattern": "$ENV{DOMAIN}", "custom_domain": true }]\n/;
      s/  \/\/ No routes yet[^\n]*\n(  \/\/[^\n]*\n)*//;
    ' wrangler.jsonc
    git --no-pager diff wrangler.jsonc
    if confirm "Commit and push this change?"; then
      run git commit -am "chore: attach $DOMAIN to the Worker as a custom domain"
      run git push -u origin chore/worker-custom-domain
      run gh pr create -R "$PORTFOLIO_REPO" --fill --base main
      say "Merge that PR once its checks pass. The deploy leaves the existing domain in place."
    else
      run git checkout -- wrangler.jsonc
      SKIPPED+=("commit the $DOMAIN custom_domain route in wrangler.jsonc")
    fi
    pause
  else
    SKIPPED+=("add the $DOMAIN custom_domain route to wrangler.jsonc")
  fi
}

# ── 7 ──────────────────────────────────────────────────────────────────
stage_disable_pages() {
  stage "Turn off the Pages project's git builds"
  say "GitHub Actions deploys the site now, so Pages should stop building every push."
  open_url "$DASH/workers-and-pages"
  step "Open the old Pages project → Settings → Builds & deployments (Branch control)."
  step "Untick 'Enable automatic production branch deployments'."
  step "Set Preview branch deployments to 'None'. Save."
  note "Keep the project for now. Once you're happy, delete it with:"
  note "  pnpm exec wrangler pages project delete <project-name>"
  pause "Press Enter once automatic Pages builds are off"
}

# ── 8 ──────────────────────────────────────────────────────────────────
stage_deploy_key() {
  stage "Deploy key for the resume sync"
  say "The private resume repo pushes its snapshot here with an SSH deploy key."
  say "This generates a key pair, adds the public half to $PORTFOLIO_REPO with write access,"
  say "stores the private half as PORTFOLIO_DEPLOY_KEY in $RESUME_REPO, then deletes both locally."
  if gh api "repos/$PORTFOLIO_REPO/branches/main/protection" >/dev/null 2>&1 \
    || [[ "$(gh api "repos/$PORTFOLIO_REPO/rulesets" --jq length 2>/dev/null || echo 0)" != "0" ]]; then
    warn "main on $PORTFOLIO_REPO has branch protection or rulesets."
    warn "Add 'Deploy keys' to the bypass list, or the sync's push to main will be rejected."
  fi
  if confirm "Generate and install the deploy key now?"; then
    key_dir=$(mktemp -d)
    cleanup_key() {
      if command -v shred >/dev/null 2>&1; then
        shred -u "$key_dir/id_ed25519" 2>/dev/null || true
      fi
      rm -rf "$key_dir"
    }
    trap cleanup_key EXIT
    ssh-keygen -q -t ed25519 -N "" -C "resume-sync@$RESUME_REPO" -f "$key_dir/id_ed25519"
    if run gh repo deploy-key add "$key_dir/id_ed25519.pub" -R "$PORTFOLIO_REPO" \
      --allow-write --title "resume sync (write)"; then
      printf '  %s✓%s deploy key added to %s\n' "$GREEN" "$RESET" "$PORTFOLIO_REPO"
      if gh secret set PORTFOLIO_DEPLOY_KEY -R "$RESUME_REPO" <"$key_dir/id_ed25519" >/dev/null 2>&1; then
        WRITTEN_SECRET+=("$RESUME_REPO:PORTFOLIO_DEPLOY_KEY")
        printf '  %s✓ set%s secret PORTFOLIO_DEPLOY_KEY on %s\n' "$GREEN" "$RESET" "$RESUME_REPO"
      else
        warn "couldn't store the private key. Delete the deploy key on $PORTFOLIO_REPO and re-run."
        SKIPPED+=("PORTFOLIO_DEPLOY_KEY on $RESUME_REPO (re-run this stage)")
      fi
    else
      warn "couldn't add the deploy key. If one titled 'resume sync (write)' exists, delete it and re-run."
      SKIPPED+=("deploy key on $PORTFOLIO_REPO")
    fi
    cleanup_key
    trap - EXIT
    printf '  %s✓%s local key files deleted\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("deploy key + PORTFOLIO_DEPLOY_KEY secret")
  fi
  pause
}

# ── 9 ──────────────────────────────────────────────────────────────────
stage_resume_sync() {
  stage "Merge the resume PR and watch the first sync"
  RESUME_PR_URL=$(gh pr view "$RESUME_PR_BRANCH" -R "$RESUME_REPO" --json url -q .url 2>/dev/null || true)
  if [[ -n "$RESUME_PR_URL" ]]; then
    open_url "$RESUME_PR_URL"
  else
    warn "no open PR found for $RESUME_PR_BRANCH; open it from https://github.com/$RESUME_REPO/pulls"
  fi
  step "Review and merge the PR. Merging to main starts the sync-portfolio workflow."
  pause "Press Enter once the PR is merged"
  if confirm "Watch the sync run now?"; then
    watch_latest_run "$RESUME_REPO" sync-portfolio.yml main
    say "Latest commit on $PORTFOLIO_REPO main:"
    note "  $(gh api "repos/$PORTFOLIO_REPO/commits/main" --jq '.commit.message' 2>/dev/null | head -n1 || true)"
    note "No new 'chore(resume): sync' commit just means the snapshot was already current."
  fi
  pause
}

# ── 10 ──────────────────────────────────────────────────────────────────
stage_analytics() {
  stage "Cloudflare Web Analytics"
  say "The site loads the analytics beacon only when PUBLIC_CF_ANALYTICS_TOKEN is set at build time."
  open_url "$DASH/web-analytics"
  step "If $DOMAIN is already listed, open Manage site. Otherwise Add a site → pick $DOMAIN → Done."
  step "In Manage site, choose 'Enable with JS Snippet installation' so Cloudflare doesn't inject"
  step "a second beacon."
  step "Copy the token value from the snippet: data-cf-beacon='{\"token\": \"…\"}'"
  ask PUBLIC_CF_ANALYTICS_TOKEN "Paste the site token:"
  note "Not written to .env, so local builds don't report page views."
  set_repo_var "$PORTFOLIO_REPO" PUBLIC_CF_ANALYTICS_TOKEN "$PUBLIC_CF_ANALYTICS_TOKEN"
  if confirm "Rebuild and redeploy main now so the beacon goes live?"; then
    run gh workflow run ci.yml -R "$PORTFOLIO_REPO" --ref main
    watch_latest_run "$PORTFOLIO_REPO" ci.yml main
    home_html=$(curl -s "https://$DOMAIN/" || true)
    if [[ "$home_html" == *cloudflareinsights* ]]; then
      printf '  %s✓%s the beacon is on https://%s\n' "$GREEN" "$RESET" "$DOMAIN"
    else
      warn "no beacon found on https://$DOMAIN yet; check the deploy."
    fi
  fi
  pause
}

# ── Run ──────────────────────────────────────────────────────────────────
# Pass a stage number to resume part-way, e.g. ./scripts/setup-wizard.sh 5
# Preflight always runs.
STAGES=(stage_preflight stage_cloudflare_token stage_first_deploy stage_merge_portfolio stage_move_domain stage_declare_domain stage_disable_pages stage_deploy_key stage_resume_sync stage_analytics)
START_AT="${1:-1}"
TOTAL_STAGES=${#STAGES[@]}

banner "tiencheng.dev: Cloudflare Workers cutover and resume sync"
for i in "${!STAGES[@]}"; do
  if (( i > 0 && i + 1 < START_AT )); then
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    continue
  fi
  "${STAGES[$i]}"
done

finish
